services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=dynamodb,sqs,sns,lambda
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "resaleorder_data:/var/lib/localstack"

  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform
    working_dir: /app
    depends_on:
      - localstack
    volumes:
      - ./infrastructure:/app
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        terraform init
        terraform apply -auto-approve

  resaleapi:
    build:
      context: ./resale-api
      dockerfile: Dockerfile
    container_name: resaleapi
    depends_on:
      terraform:
        condition: service_completed_successfully
    ports:
      - "8081:8081"

  orderapi:
    build:
      context: ./order-api
      dockerfile: Dockerfile
    container_name: orderapi
    depends_on:
      terraform:
        condition: service_completed_successfully
    ports:
      - "8082:8082"

  unstableapi:
    build:
      context: ./fake-unstable-ordering-api
      dockerfile: Dockerfile
    container_name: unstableapi
    ports:
      - "3000:3000"

volumes:
  resaleorder_data:
